name: Build, publish, and deploy Frontend Docker image to EC2

on:
  push:
    branches:
      - kritan

jobs:
  build-publish-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List directory contents at root
        run: ls -al

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push frontend Docker image
        run: |
          ls -al
          docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
            sudo docker stop frontend_container || true
            sudo docker rm frontend_container || true
            sudo docker run -d -p 3000:80 --name frontend_container ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest